name: cloud_music_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  audioplayers: ^4.0.1
  dio: ^5.1.1
  cached_network_image: ^3.2.3
  flutter_screenutil: ^5.7.0
  flutter_native_splash: ^2.2.19
  google_nav_bar: ^5.0.6
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

